version: 2.1
jobs:
  deploy:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:latest
    steps:
      - add_ssh_keys:
          fingerprints:
            - "2c:17:d2:cb:b6:96:76:cc:76:20:b9:9b:bd:75:bf:3f"
      - checkout
      - restore_cache:
          keys:
            - npm-{{ checksum "package-lock.json" }}
            - npm-

      - run:
          name: Install Dependency
          command: yarn

      - run:
          name: Build
          command: yarn generate

      - save_cache:
          key: npm-{{ checksum "package-lock.json" }}
          paths:
            - ~/workspace/node_modules
          force: yes
      - run:
          name: Git setup
          command: git config user.email "circleci" && git config user.name "circleci"

      - run:
          name: Clone deploy repo
          command: git clone git@github.com:AizuGeekDojo/AizuGeekDojo.github.io.git

      - run:
          name: Replace web page
          command: cd AizuGeekDojo.github.io && rm -rf * && cp -r ../dist/* . && git add . && git commit -m "Update."
      - run:
          name: Push to deploy
          command: git push

workflows:
  version: 2
  build_test:
    jobs:
      - deploy:
          filters:
            branches:
              only: master

